In [1]:
import sys
sys.path.append('../..')

import numpy as np
import pandas as pd
import eeg_decoder as eeg_decoder

%load_ext autoreload
%autoreload 2

In [2]:
experiment_name = 'd01'
data_dir = f'./data/{experiment_name}'
exp = eeg_decoder.Experiment(experiment_name,data_dir,dev=False,info_from_file=True)
exp.behavior_files = sorted(list(exp.data_dir.glob('*behavior.csv')))

In [3]:
exp.xdata_files

[WindowsPath('data/d01/d01_04_xdata.mat'),
 WindowsPath('data/d01/d01_06_xdata.mat'),
 WindowsPath('data/d01/d01_07_xdata.mat'),
 WindowsPath('data/d01/d01_08_xdata.mat'),
 WindowsPath('data/d01/d01_09_xdata.mat'),
 WindowsPath('data/d01/d01_10_xdata.mat'),
 WindowsPath('data/d01/d01_11_xdata.mat'),
 WindowsPath('data/d01/d01_12_xdata.mat'),
 WindowsPath('data/d01/d01_13_xdata.mat'),
 WindowsPath('data/d01/d01_14_xdata.mat'),
 WindowsPath('data/d01/d01_16_xdata.mat'),
 WindowsPath('data/d01/d01_17_xdata.mat'),
 WindowsPath('data/d01/d01_19_xdata.mat'),
 WindowsPath('data/d01/d01_20_xdata.mat'),
 WindowsPath('data/d01/d01_21_xdata.mat'),
 WindowsPath('data/d01/d01_22_xdata.mat'),
 WindowsPath('data/d01/d01_23_xdata.mat'),
 WindowsPath('data/d01/d01_24_xdata.mat'),
 WindowsPath('data/d01/d01_25_xdata.mat'),
 WindowsPath('data/d01/d01_26_xdata.mat'),
 WindowsPath('data/d01/d01_27_xdata.mat'),
 WindowsPath('data/d01/d01_28_xdata.mat'),
 WindowsPath('data/d01/d01_29_xdata.mat'),
 WindowsPat

In [4]:

not_enough_data = []
behavior_no_match = []

for isub in range(exp.nsub):
    print(exp.xdata_files[isub])
    xdata,ydata = exp.load_eeg(isub)

    # Check enough data
    _,cond_counts = np.unique(ydata,return_counts=True)
    cond_counts = np.delete(cond_counts,3)
    print(cond_counts)
    check_enough_data = np.all(cond_counts>175)

    if check_enough_data == False:
        not_enough_data.append(isub)

    # Check data files align
    noArt_idx = exp.load_artifact_idx(isub)
    assert xdata.shape[0]==noArt_idx.sum()

    behavior = pd.read_csv(exp.behavior_files[isub])
    behavior = behavior[behavior.Block.notnull()] # cut out original post-task stuff
    
    if len(behavior)!=noArt_idx.shape[0]:
        behavior_no_match.append(isub)


data\d01\d01_04_xdata.mat
[239 230 241]
data\d01\d01_06_xdata.mat
[283 283 261]
data\d01\d01_07_xdata.mat
[191 187 181]
data\d01\d01_08_xdata.mat
[224 222 206]
data\d01\d01_09_xdata.mat
[275 281 271]
data\d01\d01_10_xdata.mat
[284 284 288]
data\d01\d01_11_xdata.mat
[248 276 260]
data\d01\d01_12_xdata.mat
[251 255 241]
data\d01\d01_13_xdata.mat
[250 255 245]
data\d01\d01_14_xdata.mat
[272 268 273]
data\d01\d01_16_xdata.mat
[267 270 278]
data\d01\d01_17_xdata.mat
[267 259 253]
data\d01\d01_19_xdata.mat
[263 276 275]
data\d01\d01_20_xdata.mat
[230 223 217]
data\d01\d01_21_xdata.mat
[236 239 228]
data\d01\d01_22_xdata.mat
[239 232 235]
data\d01\d01_23_xdata.mat
[242 247 246]
data\d01\d01_24_xdata.mat
[282 278 268]
data\d01\d01_25_xdata.mat
[186 205 194]
data\d01\d01_26_xdata.mat
[261 263 252]
data\d01\d01_27_xdata.mat
[242 227 209]
data\d01\d01_28_xdata.mat
[264 262 269]
data\d01\d01_29_xdata.mat
[273 270 258]
data\d01\d01_30_xdata.mat
[277 269 254]


In [5]:
print(np.array(exp.xdata_files)[not_enough_data])
print(behavior_no_match)

[]
[]
